language: node_js
node_js:
- '8'
- '10'
deploy:
  provider: npm
  email: admin@cmr1.com
  on:
    tags: true
    repo: cmr1/node-cli
  api_key:
    secure: Lv/pYF6C63YegJqBRQVKczof3rRxDQztcDdYeWrrQv1ZoUcLm+4FJ9wdMsemZO/BLot6s4BQwVrjsGf4wKHinxqd7g7chFSlftGAK0B/YSCfXjmMymuc5vCTq7fQULMk66ua4qvmv4sVqfKZyf3jkWFAENtvlTdTjxZ8N0SS6+w8R+bsOCVxb9TTM9G0J1yae3SbW7HLKSXEp01/E1MQihrfu/Byp25DmUb29qEZ6NH+FkFHXbjIOqDdyk4Ig+L33mCHpAd/d1Mz8+0a83mHzHVlwfqr3eYvSh87bDAm1UqW5Iunuy+6cT2JO35TJUDfpaiuT5oIRBkFRq2wRh0T+uFsjW6JzWzSHU4WB4TLikk6c/CHVf902a3a12G50ZqVhE/zX+7UWfUzGRD8QiCQVm3fqEiP1zdqqmZnxWQyiCfuLP26x0GI3P1VC8U8Sq4qb1ZI6eqxL8BK31Nlx7t3Dd8WzFOdCHV72hubwKTVSl6DWyLXg2fajeyCGTAcMUk6aphK0npMmLCz154Hi2da2klfLbTBv7avgIAnI/j7fqQ+S1lozQpT+Z2wor+2rGN7OTal8bwRGo0/GpdtdKRpHZ53BRug5ZkBZTNGHgc3ZlaIG4b4RoKoE7AReZZHi51fFa1/ehJrJ35bpo4fdKaEpIT2zVyoDMO+kiHKeo7wn/E=
notifications:
  slack:
    secure: cnijnTuf1GTfFZ2zpj3BN/Sv0+wTl4R5fM7wbxn/0QMUMN3tz6gqDCfKsSqkzM6P1/JSgVZNlnGQuzJZZjHvxkOlGREaEPBDFCnmFsz+Pl7OdPyGMMLKCKSR714Dd1/YI5YCa9yv3xMZ5CAAtfKVohxuIalqSTHqU6xMXRI990kYqeOjpZQUryzVo56GGeijjU2WxXQLYgaL5BPJATQeF+qq1lQ8ulXO5O7q2/nvzKhE42hSBJM0dC1BWznZ8aTfDChCjxNTwCpKavicKHuOMsiMduEoUVp1m/tsxQ9LPRWP6ZYrn3Z+o5c7AuWraUzQYtpGToz2UHR0iz35FMCJBOLypwxKRHBxFmR7fW7DRGjk3wCU/7R1xtGiXRP79215ZQMzlHP7hcZ1w8iVRL27MLvOKiDSD3q27n3pAjjSaA6anUmQjx7ZwMUjxjrSgEFTgk40Q6zCcsOwYAPvIj+tkWSWohatZGk77XyuUjxdLYIM/uSMWpSmZQ9WgV6+YHmg9KmZxBmYk+i+v9JZwPX8MiY2qdllnW7axQ2+zQCqHNUjgbMr3n7rSVPEl2LKs4IWs773NT+3bLooj5b9uUSJ4xdz/5lWYEHPOZPXqdAJXsupMJtY+RP01NTTFCDtKj3t7PJvOSUm7KiWl6uuxjf8y7SLColaxUXvhgXmCZ9xaUc=
