language: node_js
node_js:
- 6.0.0
- 6.9.4
- 7.0.0
- 7.4.0
deploy:
  provider: npm
  email: admin@cmr1.com
  api_key:
    secure: QahMPoX+N5e7blguwQCFsinZqpZQydPKIXGNDAaqYD+10W3hzm4CNGl1/FC2J3yorWk8CSKHpcPbQ74Hm100dtEE2ceukkJa7fiTg2YdTu/W8WfmpB5UYDhln7aL6hpT3dB3uzmA7QfjoniUGfOO9MvW1Z7gWmtm6BY6CcYfewoZW7C93yll+jQbFaA1NiSaTCwdaycgH2pd0I3T7pN+7b2J+wZvB7PhOrKUS5SYivHSvsom29rKZF8iBoXf7uwIohtkAUX0DsR1hy8wBXi5JsE7NelAABAdH8gHB6auXpRP0akoK94D8ehwGpHaTzJYg8KDuo6F9L5mWq928XdozgRBdYFhW1DDkBSqstSAueXdc+GJnRFR9wr2w14uE+BIJFZ+IUICrqnnbgHw2As6uXm3TgPtBJJN96h27fxZkn4rbTS5Qil7bYK/JfYjYAdAIbxLGIHms3avgCxaE4DBchOo8vNAw7Wv2cs5SKvk5O2yQ3MPMKcPs5RlLdX1gSQ6K0jdhm4xwciY2x/SY/Tr4zQ5Sk3GvUq8V585/Z7rnTj7myU2xE6xjPknfc6d8k92BDikAo97VGMeEt0qPPhN9tv6wzFGreGvy+9Zvr1n88yjlMuG1hg0S04T4UYgUR91UbXVS4qqugD7lmTfqDfaOrSu3fBmXQKgh0rDquUOmCE=
  on:
    tags: true
    repo: cmr1/cli-node
