language: node_js
node_js:
- 6.0.0
- 6.9.4
- 7.0.0
- 7.4.0
deploy:
  provider: npm
  email: admin@cmr1.com
  api_key:
    secure: n/vlW02khFWuzBjXb8n85a+2gRrMX7TZOzh77hDMuh6ULTwjiTq16G+cfE6vAf/SmepRmj2Cqp8ja0ldsbCJRczcwltijDCzcePB/0gEVJhIxitiKBpSzsl9fCV49dccQjXvLRq+KKPEGNgn2V/2RZbvZu/MXHhQrOmXuHGyMYuIUrMAq4Pfytor5CG3+Mo+f/E+fP4cpc48O0rAg5DOfGZBvwXxTK3121J9Q3kVBrafFcAgF2g4Y+kZz3snruMWH/QtkHLSHeBdcpUZCYamLws8dSaltFjnaZ9Vm/zzXO14Y/++nMmucPXwV1sFqJu4/WY4nQWGQRqnPorRIQhhenKEmHbqnTZ0NB44CgDhluaNCNzjhsNAYYeoUCO+O1Tm0EniJFihrqvyOTK9Kb121fjYMJO+BxLHORNv8/J+HYqmsAHo2xMfijaLDKM3Fo6SMuOF6wsQgCqcJ73XZNbos4GLirfGlGueipT35ZOIrjKbQ+t11eyUaj7agLM/Mk6boxdQYrDi05wGlr+x5gimcJRnty6EJ5dqp3jq3zdnV63dkv69Sr8jq8WBXHU6aZCWDZNa0/41oQ5OTSGHt7FX1rHiQycggzaCe90ff69mdni/WBVp2t8PfxlN1hXfKhC+TkxQ6skGrxjtGjc5dQpIrpbtrBDj+IEAhlYEax7wNo4=
  on:
    tags: true
    repo: cmr1/cli-node
